### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by matty575** [tombell/passport-monzo#2]
Hi Tom,

This strategy is tailored to connecting with a pre determined monzo user.

I am trying to build an nodejs application that will ask users to log in using monzo oauth2, asking them to provide their client_id and client_secret before doing so.

But I cannot seem to be able to provide the client_id and client_secret to the strategy via a login route and then process the authentication.

Do you know how I would accomplish this? Sorry if this is daft question but I am pretty new to oauth2 authentication.

Regards,

Matty

**Comment by tombell** [comment]
Currently this is a limitation with the Monzo API, from the API docs:

> The Monzo Developer API is not suitable for building public applications.
> You may only connect to your own account or those of a small set of users you explicitly whitelist.
> Please read our blog post for more detail.

So while currently you can only connect to your own Monzo account, this library will work as normal like other OAuth providers, where any user can login to auth.

Hope this explains the situation, there is anything we can do until the API moves into the next phase.

**Comment by matty575** [comment]
Hi Tom,

Thanks for the prompt reply. Yes I saw that the monzo api wasn't suitable for public applications.

My interest is purely for my sole use. I would like to create an application that mimics a joint account since Monzo won't provide it for sometime. 

So I would just like to build a simple application that ask a user (me and my partner) to log in using their monzo api credentials and then I would store their credentials, access token and refresh token in a db. I would then just use these credentials to pull the balance and if needed refresh the token when it expires.

My stumbling block is trying to add the client_id and client_secret from the user entering them via a login page. Everytime I put the strategy code and authentication code not in the application main code but in a function or route then when I call authenticate the app just hangs.

I am pretty sure it is down to where the strategy is declared. But I will keep on playing. If you can think of anything that may help let me know otherwise close the issue down.

Cheers,

Matty
